### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by AntonioGiovanniSchiavone** [peppelinux/spid-sp-test#11]
Following the instruction and launching the command:

`` sudo pip install spid-sp-test --upgrade --no-cache``

I get the following error:

```
Collecting spid-sp-test
  Downloading https://files.pythonhosted.org/packages/f2/92/4947c4b88ab7aa5fc1974082d7a5b9c2a7b5488ab2706146083aba443456/spid_sp_test-0.5.0.tar.gz (55kB)
    100% |████████████████████████████████| 61kB 4.1MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-TqWLIA/spid-sp-test/setup.py", line 25
        packages=[f"{_pkg_name}"],
                               ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-TqWLIA/spid-sp-test/
```

Tested on elementary OS 5.1.7 Hera (based on Ubuntu 18.04 LTS)

**Comment by AntonioGiovanniSchiavone** [comment]
Solved forcing to use pip3 instead of pip2 and upgrading pip3.

Maybe in README you should specify that the tool is only compatible with python3/pip3

**Comment by peppelinux** [comment]
added badges here: https://github.com/italia/spid-sp-test/commit/09a842ee27a4f007211525ad1258a87bf157ebd0

thank you!
